package com.example.abacus_app;

import com.google.firebase.Timestamp;
import com.google.firebase.firestore.PropertyName;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing an Event in the system.
 * Contains information about the event details, registration period,
 * capacity limits, and organizer settings.
 *
 * @author Himesh
 * @version 1.0
 */
public class Event implements Serializable {
    private String eventId;
    private String title;
    private String description;
    private String organizerId;
    private String organizerEmail;
    private Timestamp registrationStart;
    private Timestamp registrationEnd;
    private Timestamp eventStart;
    private Timestamp eventEnd;
    private Integer waitlistCapacity;
    private Integer eventCapacity;
    private Integer waitlistCount;    // Current number of people on waitlist
    private boolean geoRequired;
    private boolean lotteryDrawn;
    @PropertyName("isPrivate")
    private boolean isPrivate;
    private String posterImageUrl;
    private String qrCodeUrl;
    private List<String> coOrganizers = new ArrayList<>();
    private Boolean isDeleted;
    private List<String> tags = new ArrayList<>();

    public Event() {}

    /**
     * Constructs a new Event with mandatory fields.
     *
     * @param eventId           The unique ID generated by Firestore.
     * @param title             The name of the event.
     * @param description       Detailed information about the event.
     * @param organizerId       The ID of the organizer who created it.
     * @param registrationStart When entrants can start joining the waitlist.
     * @param registrationEnd   When registration closes.
     * @param waitlistCapacity  Max entrants allowed (null if unlimited).
     * @param geoRequired       Whether entrants must provide geolocation.
     * @param lotteryDrawn      Whether the lottery has been run.
     */
    public Event(String eventId, String title, String description, String organizerId,
                 Timestamp registrationStart, Timestamp registrationEnd,
                 Integer waitlistCapacity, Integer eventCapacity, boolean geoRequired, boolean lotteryDrawn) {
        this.eventId = eventId;
        this.title = title;
        this.description = description;
        this.organizerId = organizerId;
        this.registrationStart = registrationStart;
        this.registrationEnd = registrationEnd;
        this.waitlistCapacity = waitlistCapacity;
        this.eventCapacity = eventCapacity;
        this.geoRequired = geoRequired;
        this.lotteryDrawn = lotteryDrawn;
        this.coOrganizers = new ArrayList<>();
        this.isPrivate = false; // Default to public
    }

    /**
     * @return the unique ID of the event.
     */
    public String getEventId() { return eventId; }

    /**
     * @param eventId sets the unique ID of the event.
     */
    public void setEventId(String eventId) { this.eventId = eventId; }

    /**
     * @return the display title.
     */
    public String getTitle() { return title; }

    /**
     * @param title sets the display title.
     */
    public void setTitle(String title) { this.title = title; }

    /**
     * @return the event description.
     */
    public String getDescription() { return description; }
    
    /**
     * @param description sets the event description.
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * @return the organizer's ID.
     */
    public String getOrganizerId() { return organizerId; }
    
    /**
     * @param organizerId sets the organizer's ID.
     */
    public void setOrganizerId(String organizerId) { this.organizerId = organizerId; }

    public String getOrganizerEmail() { return organizerEmail; }
    public void setOrganizerEmail(String organizerEmail) { this.organizerEmail = organizerEmail; }

    /**
     * @return start of registration period.
     */
    public Timestamp getRegistrationStart() { return registrationStart; }
    
    /**
     * @param registrationStart sets registration start time.
     */
    public void setRegistrationStart(Timestamp registrationStart) { this.registrationStart = registrationStart; }

    /**
     * @return end of registration period.
     */
    public Timestamp getRegistrationEnd() { return registrationEnd; }
    
    /**
     * @param registrationEnd sets registration end time.
     */
    public void setRegistrationEnd(Timestamp registrationEnd) { this.registrationEnd = registrationEnd; }

    /** When the event itself starts (shown to entrants). */
    public Timestamp getEventStart() { return eventStart; }
    public void setEventStart(Timestamp eventStart) { this.eventStart = eventStart; }

    /** When the event itself ends (shown to entrants). */
    public Timestamp getEventEnd() { return eventEnd; }
    public void setEventEnd(Timestamp eventEnd) { this.eventEnd = eventEnd; }

    public Integer getWaitlistCapacity() { return waitlistCapacity; }
    public void setWaitlistCapacity(Integer waitlistCapacity) { this.waitlistCapacity = waitlistCapacity; }

    public Integer getEventCapacity() { return eventCapacity; }
    public void setEventCapacity(Integer eventCapacity) { this.eventCapacity = eventCapacity; }

    public Integer getWaitlistCount() { return waitlistCount; }
    public void setWaitlistCount(Integer waitlistCount) { this.waitlistCount = waitlistCount; }

    public boolean isGeoRequired() { return geoRequired; }
    public void setGeoRequired(boolean geoRequired) { this.geoRequired = geoRequired; }

    public boolean isLotteryDrawn() { return lotteryDrawn; }
    public void setLotteryDrawn(boolean lotteryDrawn) { this.lotteryDrawn = lotteryDrawn; }

    @PropertyName("isPrivate")
    public boolean isPrivate() { return isPrivate; }

    @PropertyName("isPrivate")
    public void setPrivate(boolean isPrivate) { this.isPrivate = isPrivate; }
    public String getPosterImageUrl() { return posterImageUrl; }
    public void setPosterImageUrl(String posterImageUrl) { this.posterImageUrl = posterImageUrl; }

    public String getQrCodeUrl() { return qrCodeUrl; }
    public void setQrCodeUrl(String qrCodeUrl) { this.qrCodeUrl = qrCodeUrl; }

    public List<String> getCoOrganizers() { return coOrganizers; }
    public void setCoOrganizers(List<String> coOrganizers) { this.coOrganizers = coOrganizers; }

    public Boolean getIsDeleted() { return isDeleted; }
    public void setIsDeleted(Boolean isDeleted) { this.isDeleted = isDeleted; }

    public List<String> getTags() { return tags; }
    public void setTags(List<String> tags) { this.tags = tags; }
}